default: &default
  encoding: unicode
  min_messages: WARNING
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: mealz

development:
  <<: *default
  database: mealz_dev

test:
  <<: *default
  database: mealz_test
